import duality_theorems_locally_compact_groups_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace duality_theorems_locally_compact_groups_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end duality_theorems_locally_compact_groups_theorem_canonical_lane_mathlib
end HautevilleHouse
